name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck-action
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check_library: enable
          skip_preprocessor: disable
          enable: style,performance,portability
          exclude_check: ./Arduino
          inconclusive: enable
          inline_suppression: disabe
          force_language: c,c++
          force: disable
          max_ctu_depth: 2
          platform: win64
          std: c11,c++20
          output_file: ./cppcheck_report.txt

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
